# Generated by Django 5.1.4 on 2025-03-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
