# Generated by Django 5.1.3 on 2024-12-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
