# Generated by Django 5.1.3 on 2025-01-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0002_alter_item_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discription',
            new_name='description',
        ),
    ]
