# Generated by Django 5.1.4 on 2025-03-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0002_order_shipping_order_tax_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
