# Generated by Django 5.1.4 on 2025-03-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0003_order_size_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size_factor',
        ),
    ]
