# Generated by Django 5.1.4 on 2025-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0004_remove_order_size_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_oriented_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
