# Generated by Django 5.1.4 on 2025-03-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
