# Generated by Django 5.1.4 on 2025-03-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0005_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
