# Generated by Django 5.1.3 on 2025-01-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0007_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='District',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='ZipCode',
            new_name='zipcode',
        ),
    ]
