# Generated by Django 5.1.3 on 2025-01-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0008_rename_city_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.IntegerField(blank=True, choices=[(1, 'permanent'), (2, 'temporary')], null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
