# Generated by Django 5.1.3 on 2025-02-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0009_address_address_type_alter_address_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, [(4, 'S'), (5, 'M'), (6, 'L')]), (2, [(1, 'Quarter'), (2, 'Half'), (3, 'Full')]), (3, [(5, 'Regular'), (6, 'Large')])], null=True),
        ),
    ]
