# Generated by Django 5.1.3 on 2025-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0010_alter_cart_size_alter_item_category_alter_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Category1'), (2, 'Category2'), (3, 'Category3')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
