# Generated by Django 5.1.3 on 2025-02-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0011_item_category_type_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Category1(S,M,L)'), (2, 'Category2(Quarter,Half,Full'), (3, 'Category3(regular,large)')], null=True),
        ),
    ]
