# Generated by Django 5.1.3 on 2025-02-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0012_alter_item_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Category1(S,M,L)'), (2, 'Category2(Quarter,Half,Full)'), (3, 'Category3(regular,large)')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, [('S', 'Small'), ('M', 'Medium'), ('L', 'Large')]), (2, [('R', 'Regular'), ('L', 'Large')]), (3, [('Q', 'Quarter'), ('H', 'Half'), ('F', 'Full')])], null=True),
        ),
    ]
