# Generated by Django 5.1.3 on 2025-02-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0014_alter_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, [('S', 'Small'), ('M', 'Medium'), ('L', 'Large')]), (2, [('Q', 'Quarter'), ('H', 'Half'), ('F', 'Full')]), (3, [('R', 'Regular'), ('L', 'Large')])], null=True),
        ),
    ]
