# Generated by Django 5.1.3 on 2025-03-11 07:35

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DINGO_APP', '0015_alter_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='DINGO_APP.address'),
        ),
    ]
